### ISSUE TITLE
Connect to DB

### ISSUE THREAD

**Issue by Kryniek** [Kryniek/Russia2018WorldCupApi#1]

**Comment by Kryniek** [comment]
URL: "mongodb://lewandowski:asseco123@worldcup2018-russia-2018-world-cup.7e14.starter-us-west-2.openshiftapps.com/worldcup"

Login: "lewandowski"
Pass: "asseco123"

**Comment by bskorka** [comment]
Przez problemy z wyciągnięciem Mongo z Openshifta na zewnątrz na razie założyłem takie na mLab:

```
ds147450.mlab.com:47450
database: worldcup2018api 
-u lewandowski
-p asseco123
```

wartość property dla springa:
`spring.data.mongodb.uri = mongodb://lewandowski:asseco123@ds147450.mlab.com:47450/worldcup2018api`

**Comment by bskorka** [comment]
Resolved in pull request #11 - issue can be closed.
