### ISSUE TITLE
Jackson JSON in third part Api call

### ISSUE THREAD

**Issue by Kryniek** [Kryniek/Russia2018WorldCupApi#15]
Use Jackson in third part api calling.

**Comment by bskorka** [comment]
If we want to update league standings (group standings) and events (matches) information we should run cron every time the match is over. If we want to update matches by live information (every 5/10/15? minutes) we should think how to make it.

Basic code behaviour (not finished yet):
For leagues:
- call API
- check if all league_ids exist in our database, if yes - do nothing - find by leagueId, limit?
- if new leagues will appear under country "World Cup 2018" that will mean that we should add this records to database and the playoff stage started

Events (matches)
- if date/time of event/fixture is lower than actual time we should update record in our database cause that may attach some information of goalscorers and result.
