### ISSUE TITLE
Storing matches issue

### ISSUE THREAD

**Issue by bskorka** [Kryniek/Russia2018WorldCupApi#20]
If league object would store Standings and Matches it would be easier for us to display that data. There would be few documents in the database so there is no need to think about performance ATM.

Issue I am thinking about is that we would like to have a dashboard which will display today matches. Api calling gives us opportunity to get today matches of World Cup without narrowing query to leagueId (calling by country_id - World Cup const). It would be better to sync today matches once a day and than store it in DB in different collection than leagues or write query to DB which will get us a list of today matches from league collection.

**Comment by Kryniek** [comment]
we will discuss that
