### ISSUE TITLE
Betting collection

### ISSUE THREAD

**Issue by bskorka** [Kryniek/Russia2018WorldCupApi#21]
I was thinking about something like that:
```
{
bets : [{
  type : enum(WORLD_CUP_WINNER)
  betTypeId : const for WORLD_CUP_WINNER
  value : "Saudi Arabia",
  login : "aaa",
  status : "OPENED",
  points : 0 // updated after the event
}, {
  type : enum (GROUP_STAGE_PROMOTION)
  betTypeId : const for GROUP_STAGE_PROMOTION
  value : "Poland, Columbia"
  login: "bbb",
  points : 0
}, {
  type : enum (MATCH_RESULT)
  betTypeId : matchId,
  value : // ? - how to keep score, how to keep extratime/penalties score, another fields? 
// It could be a little bit different model (extend basic one) and be stored in same collection -
// mongoDB love
  login : "aaa",
  points : 0
}]
}

```

**Comment by Kryniek** [comment]
> enum (GROUP_STAGE_PROMOTION)
value : "Poland, Columbia"

If first team will be the team that leave group stage from 1st place and second team from 2nd place then it's correct. Otherwise we could do something like: value: {firstPlace : "Poland (of course)", secondPlace: "Columbia"}

**Comment by Kryniek** [comment]
> enum (MATCH_RESULT)
value : // ? - how to keep score, how to keep extratime/penalties score, another fields? 
// It could be a little bit different model (extend basic one) and be stored in same collection -
// mongoDB love

Maybe like previous comment value:

value : {
    scoreTeam1: 1,
    scoreTeam2: 3//1:3,
    extratimeScoreTeam1: 2,
    extratimeScoreTeam2: 17,
   (...)
}
